"""
AssuranceIA™ Field-Level Encryption Module
Encrypts sensitive PII fields for GDPR/CCPA compliance
"""

import os
import logging
from typing import Optional, Any
from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2
import base64

logger = logging.getLogger("assurancia.encryption")


class FieldEncryption:
    """
    Encrypt/decrypt sensitive fields for database storage.

    Sensitive fields (PII):
    - user_email
    - firstname
    - lastname
    - phone
    - address
    """

    # Fields that must be encrypted
    ENCRYPTED_FIELDS = {
        "user_email",
        "firstname",
        "lastname",
        "phone",
        "address",
        "description",  # Can contain personal info
    }

    def __init__(self, master_key: Optional[str] = None):
        """
        Initialize encryption with master key.

        Args:
            master_key: Encryption key (defaults to ENCRYPTION_KEY env var)

        Raises:
            ValueError: If master key not configured
        """
        self.master_key = master_key or os.getenv("ENCRYPTION_KEY", "").strip()

        if not self.master_key:
            raise ValueError(
                "ENCRYPTION_KEY not configured. Set ENCRYPTION_KEY environment variable. "
                "Generate with: python -c 'from cryptography.fernet import Fernet; "
                "print(Fernet.generate_key().decode())'"
            )

        if len(self.master_key) < 32:
            raise ValueError(
                f"ENCRYPTION_KEY too short ({len(self.master_key)} chars). "
                "Use a key generated by Fernet.generate_key()"
            )

        try:
            self.cipher = Fernet(self.master_key.encode() if isinstance(self.master_key, str) else self.master_key)
        except Exception as e:
            raise ValueError(f"Invalid ENCRYPTION_KEY format: {e}")

        logger.info("✅ Field encryption initialized")

    def encrypt(self, value: Any) -> str:
        """
        Encrypt a value.

        Args:
            value: Value to encrypt (will be converted to string)

        Returns:
            Encrypted string with 'encrypted:' prefix
        """
        if value is None:
            return None

        try:
            plaintext = str(value).encode("utf-8")
            ciphertext = self.cipher.encrypt(plaintext)
            # Return with prefix so we know it's encrypted when reading
            return f"encrypted:{ciphertext.decode('utf-8')}"
        except Exception as e:
            logger.error(f"Encryption error: {e}")
            raise

    def decrypt(self, encrypted_value: str) -> Optional[str]:
        """
        Decrypt a value.

        Args:
            encrypted_value: Encrypted value (may have 'encrypted:' prefix)

        Returns:
            Decrypted string, or original value if not encrypted
        """
        if not encrypted_value:
            return encrypted_value

        try:
            # Check for encryption prefix
            if isinstance(encrypted_value, str) and encrypted_value.startswith("encrypted:"):
                ciphertext = encrypted_value[len("encrypted:"):]
            else:
                # Not encrypted, return as-is
                return encrypted_value

            plaintext = self.cipher.decrypt(ciphertext.encode("utf-8"))
            return plaintext.decode("utf-8")
        except InvalidToken:
            logger.error("Failed to decrypt value: invalid token")
            return None
        except Exception as e:
            logger.error(f"Decryption error: {e}")
            return None

    def encrypt_claim(self, claim: dict) -> dict:
        """
        Encrypt all PII fields in a claim.

        Args:
            claim: Claim dictionary

        Returns:
            Claim with encrypted PII fields
        """
        encrypted_claim = claim.copy()

        for field in self.ENCRYPTED_FIELDS:
            if field in encrypted_claim and encrypted_claim[field]:
                try:
                    encrypted_claim[field] = self.encrypt(encrypted_claim[field])
                except Exception as e:
                    logger.warning(f"Failed to encrypt {field}: {e}")
                    # Don't fail the entire operation, just log

        return encrypted_claim

    def decrypt_claim(self, claim: dict) -> dict:
        """
        Decrypt all PII fields in a claim.

        Args:
            claim: Encrypted claim dictionary

        Returns:
            Claim with decrypted PII fields
        """
        decrypted_claim = claim.copy()

        for field in self.ENCRYPTED_FIELDS:
            if field in decrypted_claim:
                value = decrypted_claim[field]
                if isinstance(value, str) and value.startswith("encrypted:"):
                    try:
                        decrypted_claim[field] = self.decrypt(value)
                    except Exception as e:
                        logger.warning(f"Failed to decrypt {field}: {e}")
                        # Keep encrypted value if decryption fails

        return decrypted_claim

    @staticmethod
    def is_encrypted(value: str) -> bool:
        """Check if a value is encrypted"""
        return isinstance(value, str) and value.startswith("encrypted:")


class MasterKeyRotation:
    """
    Handle encryption key rotation for security compliance.

    When rotating keys:
    1. Generate new key
    2. Re-encrypt all data with new key
    3. Backup old key
    4. Update ENCRYPTION_KEY env var
    """

    def __init__(self, old_cipher: FieldEncryption, new_cipher: FieldEncryption):
        """
        Initialize key rotation.

        Args:
            old_cipher: Existing encryption instance
            new_cipher: New encryption instance
        """
        self.old_cipher = old_cipher
        self.new_cipher = new_cipher

    def rotate_claim(self, claim: dict) -> dict:
        """
        Re-encrypt a claim with new key.

        Args:
            claim: Claim with data encrypted by old key

        Returns:
            Claim with data encrypted by new key
        """
        try:
            # Decrypt with old key
            decrypted = self.old_cipher.decrypt_claim(claim)
            # Encrypt with new key
            re_encrypted = self.new_cipher.encrypt_claim(decrypted)
            return re_encrypted
        except Exception as e:
            logger.error(f"Key rotation failed for claim: {e}")
            raise

    def rotate_all_claims(self, claims_collection) -> int:
        """
        Rotate encryption key for all claims in database.

        Args:
            claims_collection: MongoDB collection of claims

        Returns:
            Number of claims rotated

        WARNING: This is a long-running operation! Run during maintenance window.
        """
        rotated = 0
        failed = 0

        try:
            for claim in claims_collection.find({}):
                try:
                    rotated_claim = self.rotate_claim(claim)
                    claims_collection.replace_one(
                        {"_id": claim["_id"]},
                        rotated_claim
                    )
                    rotated += 1
                except Exception as e:
                    logger.error(f"Failed to rotate claim {claim.get('claim_id')}: {e}")
                    failed += 1

            logger.info(f"Key rotation complete: {rotated} succeeded, {failed} failed")
            return rotated

        except Exception as e:
            logger.error(f"Key rotation aborted: {e}")
            raise


# Global encryption instance
_encryption = None


def get_encryption() -> FieldEncryption:
    """Get global encryption instance"""
    global _encryption
    if _encryption is None:
        _encryption = FieldEncryption()
    return _encryption


def initialize_encryption(master_key: Optional[str] = None) -> FieldEncryption:
    """Initialize global encryption with optional key"""
    global _encryption
    _encryption = FieldEncryption(master_key=master_key)
    return _encryption
